name: s_modal
description: A package for displaying highly customizable modal overlays including sheets, dialogs, and snackbars... with independent lifecycle management.
issue_tracker: https://github.com/SoundSliced/s_modal/issues
repository: https://github.com/SoundSliced/s_modal
version: 2.1.1
homepage: https://github.com/SoundSliced/s_modal

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  states_rebuilder_extended: ^1.0.3
  assorted_layout_widgets: ^11.0.0
  flutter_animate: ^4.5.2
  soundsliced_dart_extensions: ^1.0.1
  s_bounceable: ^2.0.0
  s_ink_button: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
