name: s_dropdown
description: "Flexible, lightweight Flutter dropdown (SDropdown) with precise overlay control, keyboard navigation, controller-based actions, item-specific styling, and responsive sizing."
license: MIT
issue_tracker: https://github.com/SoundSliced/s_dropdown/issues
repository: https://github.com/SoundSliced/s_dropdown
version: 2.1.1
homepage: https://github.com/SoundSliced/s_dropdown

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  indexscroll_listview_builder: ^2.2.0
  assorted_layout_widgets: ^11.0.0
  sizer: ^3.1.3
  soundsliced_tween_animation_builder: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
