name: keystroke_listener
description: A Flutter package for keystroke_listener functionality
issue_tracker: https://github.com/SoundSliced/keystroke_listener/issues
repository: https://github.com/SoundSliced/keystroke_listener
version: 1.1.2
homepage: https://github.com/SoundSliced/keystroke_listener

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  s_offstage: ^1.3.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
