name: s_packages_example
description: Example app showcasing all s_packages
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Local package dependencies - update paths as needed
  bubble_label:
    path: ../bubble_label
  indexscroll_listview_builder:
    path: ../indexscroll_listview_builder
  keystroke_listener:
    path: ../keystroke_listener
  pop_overlay:
    path: ../pop_overlay
  pop_this:
    path: ../pop_this
  post_frame:
    path: ../post_frame
  s_animated_tabs:
    path: ../s_animated_tabs
  s_banner:
    path: ../s_banner
  s_bounceable:
    path: ../s_bounceable
  s_button:
    path: ../s_button
  s_client:
    path: ../s_client
  s_connectivity:
    path: ../s_connectivity
  s_context_menu:
    path: ../s_context_menu
  s_disabled:
    path: ../s_disabled
  s_dropdown:
    path: ../s_dropdown
  s_error_widget:
    path: ../s_error_widget
  s_expendable_menu:
    path: ../s_expendable_menu
  s_future_button:
    path: ../s_future_button
  s_glow:
    path: ../s_glow
  s_gridview:
    path: ../s_gridview
  s_ink_button:
    path: ../s_ink_button
  s_liquid_pull_to_refresh:
    path: ../s_liquid_pull_to_refresh
  s_maintenance_button:
    path: ../s_maintenance_button
  s_modal:
    path: ../s_modal
  s_offstage:
    path: ../s_offstage
  s_screenshot:
    path: ../s_screenshot
  s_sidebar:
    path: ../s_sidebar
  s_standby:
    path: ../s_standby
  s_time:
    path: ../s_time
  s_toggle:
    path: ../s_toggle
  s_webview:
    path: ../s_webview
  s_widgets:
    path: ../s_widgets
  settings_item:
    path: ../settings_item
  shaker:
    path: ../shaker
  signals_watch:
    path: ../signals_watch
  soundsliced_dart_extensions:
    path: ../soundsliced_dart_extensions
  soundsliced_tween_animation_builder:
    path: ../soundsliced_tween_animation_builder
  states_rebuilder_extended:
    path: ../states_rebuilder_extended
  ticker_free_circular_progress_indicator:
    path: ../ticker_free_circular_progress_indicator
  week_calendar:
    path: ../week_calendar

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Override dependencies to use local path versions instead of hosted versions
# This is necessary when packages in this workspace depend on each other
dependency_overrides:
  bubble_label:
    path: ../bubble_label
  indexscroll_listview_builder:
    path: ../indexscroll_listview_builder
  keystroke_listener:
    path: ../keystroke_listener
  pop_overlay:
    path: ../pop_overlay
  pop_this:
    path: ../pop_this
  post_frame:
    path: ../post_frame
  s_animated_tabs:
    path: ../s_animated_tabs
  s_banner:
    path: ../s_banner
  s_bounceable:
    path: ../s_bounceable
  s_button:
    path: ../s_button
  s_client:
    path: ../s_client
  s_connectivity:
    path: ../s_connectivity
  s_context_menu:
    path: ../s_context_menu
  s_disabled:
    path: ../s_disabled
  s_dropdown:
    path: ../s_dropdown
  s_error_widget:
    path: ../s_error_widget
  s_expendable_menu:
    path: ../s_expendable_menu
  s_future_button:
    path: ../s_future_button
  s_glow:
    path: ../s_glow
  s_gridview:
    path: ../s_gridview
  s_ink_button:
    path: ../s_ink_button
  s_liquid_pull_to_refresh:
    path: ../s_liquid_pull_to_refresh
  s_maintenance_button:
    path: ../s_maintenance_button
  s_modal:
    path: ../s_modal
  s_offstage:
    path: ../s_offstage
  s_screenshot:
    path: ../s_screenshot
  s_sidebar:
    path: ../s_sidebar
  s_standby:
    path: ../s_standby
  s_time:
    path: ../s_time
  s_toggle:
    path: ../s_toggle
  s_webview:
    path: ../s_webview
  s_widgets:
    path: ../s_widgets
  settings_item:
    path: ../settings_item
  shaker:
    path: ../shaker
  signals_watch:
    path: ../signals_watch
  soundsliced_dart_extensions:
    path: ../soundsliced_dart_extensions
  soundsliced_tween_animation_builder:
    path: ../soundsliced_tween_animation_builder
  states_rebuilder_extended:
    path: ../states_rebuilder_extended
  ticker_free_circular_progress_indicator:
    path: ../ticker_free_circular_progress_indicator
  week_calendar:
    path: ../week_calendar

flutter:
  uses-material-design: true
