name: s_packages
description: A unified package gathering multiple widgets and tools.
issue_tracker: https://github.com/SoundSliced/s_packages/issues
repository: https://github.com/SoundSliced/s_packages
homepage: https://github.com/SoundSliced/s_packages
version: 1.4.1


environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  xid: ^1.2.1
  states_rebuilder: ^6.4.0
  signals_flutter: ^6.3.0
  sizer: ^3.1.3
  assorted_layout_widgets: ^11.0.0
  circular_countdown_timer: ^0.2.4
  pausable_timer: ^3.1.0+3 
  icons_plus: ^5.0.0
  lucide_icons: ^0.257.0
  dio: ^5.9.1
  http: ^1.6.0
  internet_connection_checker_plus: ^2.9.1+2
  nb_utils: ^7.2.0
  rxdart: ^0.28.0
  file_saver: ^0.3.1
  dart_helper_utils: ^6.0.0
  shared_preferences: ^2.5.4
  pointer_interceptor: ^0.10.1+2
  new_loading_indicator: ^1.2.1
  flutter_web_frame: ^1.0.0
  signals: ^6.3.0
  desktop_webview_window: ^0.2.3
  calendar_date_picker2: ^2.0.1
  universal_io: ^2.3.1
  path: ^1.9.1
  collection: ^1.19.1
  async: ^2.13.0
  fpdart: ^1.2.0

  # Extra packages not used in this package but included for export convenience, so users don't have to add them separately when using the widgets that depend on them.
  overlay_support: ^2.1.0 
  email_validator: ^3.0.0
  regexed_validator: ^2.0.0+1
  strings: ^4.0.1
  cryptography: ^2.9.0
  roundcheckbox: ^2.0.5
  swipeable_tile: ^2.0.1
  toastification: ^3.0.3
  sync_scroll_controller: ^1.0.1
  animated_list_plus: ^0.5.2
  google_fonts: ^8.0.1
  simple_animations: ^5.2.0
  universal_html: ^2.3.0
  webview_flutter_web: ^0.2.3+4
  webview_flutter: ^4.13.1


dependency_overrides:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  # Explicitly specify supported platforms
platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:
