name: s_gridview
description: A lightweight, customizable grid-like Flutter widget with index-based scrolling and tappable scroll indicators
issue_tracker: https://github.com/SoundSliced/s_gridview/issues
repository: https://github.com/SoundSliced/s_gridview
version: 2.0.1
homepage: https://github.com/SoundSliced/s_gridview
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  indexscroll_listview_builder: ^2.2.0
  soundsliced_dart_extensions: ^1.0.1
  assorted_layout_widgets: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: