name: s_animated_tabs
description: A Flutter package for s_animated_tabs functionality
issue_tracker: https://github.com/SoundSliced/s_animated_tabs/issues
repository: https://github.com/SoundSliced/s_animated_tabs
version: 1.0.1
homepage: https://github.com/SoundSliced/s_animated_tabs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  soundsliced_tween_animation_builder: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
