name: s_future_button
description: A Flutter package for future_button functionality
issue_tracker: https://github.com/SoundSliced/s_future_button/issues
repository: https://github.com/SoundSliced/s_future_button
version: 1.0.0
homepage: https://github.com/SoundSliced/s_future_button

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  assorted_layout_widgets: ^11.0.0
  nb_utils: ^7.1.8
  soundsliced_dart_extensions: ^1.0.1
  s_disabled: ^1.0.0
  states_rebuilder_extended: ^1.0.3
  rxdart: ^0.28.0
  ticker_free_circular_progress_indicator: ^1.0.0
  soundsliced_tween_animation_builder: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_async: ^1.3.1

flutter:
  uses-material-design: true