name: bubble_label
description: A small Flutter package that shows a floating bubble label anchored to a child widget, and optional background overlay + simple show/dismiss animations.
license: MIT
issue_tracker: https://github.com/SoundSliced/bubble_label/issues
repository: https://github.com/SoundSliced/bubble_label
version: 5.1.0
homepage: https://github.com/SoundSliced/bubble_label

screenshots:
  - description: 'Bubble label example showing tap and long-press interactions with overlay and animation toggles'
    path: example/assets/example.gif

topics:
  - ui
  - overlay
  - tooltip
  - bubble
  - widget

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  assorted_layout_widgets: ^11.0.0
  flutter_animate: ^4.5.2
  states_rebuilder_extended: ^1.0.3
  soundsliced_dart_extensions: ^1.0.1
  sizer: ^3.1.3
  xid: ^1.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
