name: s_connectivity_example
description: Example app demonstrating s_connectivity features
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_connectivity:
    path: ../
  sizer: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: any

flutter:
  uses-material-design: true
