name: s_disabled
description: A customizable Flutter widget for disabling and visually indicating disabled state of child widgets with optional opacity changes and tap detection.
issue_tracker: https://github.com/SoundSliced/s_disabled/issues
repository: https://github.com/SoundSliced/s_disabled
version: 1.0.0
homepage: https://github.com/SoundSliced/s_disabled

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  soundsliced_tween_animation_builder: ^1.2.0
  soundsliced_dart_extensions: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
