name: s_button
description: "A customizable button widget that supports various interactions and visual effects."
version: 1.2.1
homepage: https://github.com/SoundSliced/s_button
repository: https://github.com/SoundSliced/s_button
issue_tracker: https://github.com/SoundSliced/s_button/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  soundsliced_tween_animation_builder: ^1.2.0
  bubble_label: ^5.1.0
  ticker_free_circular_progress_indicator: ^1.0.0
  s_ink_button: ^1.1.0
  soundsliced_dart_extensions: ^1.0.1
  s_disabled: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: