name: pop_this
description: A powerful and customizable Flutter package for managing popups, toasts, and overlays with support for animations, stacking, and timers.
version: 2.0.1
homepage: https://github.com/SoundSliced/pop_this
repository: https://github.com/SoundSliced/pop_this
issue_tracker: https://github.com/SoundSliced/pop_this/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pausable_timer: ^3.1.0+3
  lucide_icons: ^0.257.0
  circular_countdown_timer: ^0.2.4
  states_rebuilder_extended: ^1.0.3
  soundsliced_dart_extensions: ^1.0.1
  sizer: ^3.1.3
  s_button: ^1.2.1
  assorted_layout_widgets: ^11.0.0
  flutter_animate: ^4.5.2
  icons_plus: ^5.0.0
  soundsliced_tween_animation_builder: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
