name: s_connectivity
description: A small Flutter utility package to detect Internet connectivity changes and show readyâ€‘toâ€‘use offline UI components
version: 1.0.1
repository: https://github.com/SoundSliced/s_connectivity
issue_tracker: https://github.com/SoundSliced/s_connectivity/issues
homepage: https://github.com/SoundSliced/s_connectivity

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  internet_connection_checker_plus: ^2.9.1+2
  assorted_layout_widgets: ^11.0.0
  sizer: ^3.1.3
  soundsliced_dart_extensions: ^1.0.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
